version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  webapp:
    build: .
    command: python /src/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/src/
    ports:
    - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
